### ISSUE TITLE
Missing import property in OpensearchAsyncClientOptions

### ISSUE THREAD

**Issue by azuken** [neoatlan/nestjs-opensearch#1]
Hi, 

I've just tried your lib and seems to be fine, but I must import a service to authenticate to AWS Opensearch, and forRootAsync cannot accept import option to import module.

Is it possible to add this ? Like other popular modules, Elasticsearch, TypeORM, Sentry...

It seems that only extend ModuleAsyncOptions interface with Pick<ModuleMetadata, 'imports'> do the trick !

**Comment by neoatlan** [comment]
@azuken Thank you for your suggestion. I am going to add that right away.

**Comment by neoatlan** [comment]
`imports` property has been added in v0.3.0

**Comment by azuken** [comment]
Thanks !
